package com.idsr.mobile.models.APIModels;
//const result = await axios.post('http://localhost:8080/api/newImmuProgEntry', {
//        formData: this.formData,
//        immunisationData: this.loadedData[0],
//        TCLID: this.$route.query.TCLID
//      });
//formData: {
//        patient: {
//          patientID: '',
//          epiID: '',
//          lastName: '',
//          firstName: '',
//          midName: '',
//          currHouseStreet: '',
//          currBrgy: '',
//          currCity: '',
//          permHouseStreet: '',
//          permBrgy: '',
//          permCity: '',
//          sex: '',
//          birthDate: '',
//          ageNo: '',
//          ageType: '',
//          admitStatus: '',
//          civilStatus: '',
//          occupation: '',
//          occuLoc: '',
//          occuStreet: '',
//          occuCity: '',
//          occuBrgy: '',
//          occuAddrID: '',
//          guardianName: '',
//          guardianContact: '',
//          indGroup: '',
//          pregWeeks: '',
//          HCPN: '',
//          ILHZ: '',
//        },
//        riskFactors: {
//          caseID: '',
//          LAlcoholism: '',
//          LDrugUse: '',
//          LPhysicalInactivity: '',
//          LSmoking: '',
//          LOthers: '',
//          CAsthma: '',
//          CHereditary: '',
//          COthers: '',
//          HDiabetes: '',
//          HHeartDisease: '',
//          HHypertension: '',
//          HObesity: '',
//          HOthers: '',
//          OAirPollution: '',
//          OCleanWater: '',
//          OFlooding: '',
//          OHealthEdu: '',
//          OHealthFacility: '',
//          OPoverty: '',
//          OShelter: '',
//          OWasteMgmt: '',
//          OVacCoverage: '',
//          OOthers: '',
//        },
//        immunization: {}
//      },
public class ProgEntry {
	private String formData, immunisationData, TCLID;

}
